name: MTProto Hunter Bot

on:
  schedule:
    # Запуск каждые 12 часов (в 00:00 и 12:00)
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Кнопка для ручного запуска, чтобы тестировать

# Даем боту права на запись в твой репозиторий
permissions:
  contents: write

jobs:
  hunt-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Parser
        env:
          # Токен нужен для жесткого поиска по чужим репам на самом GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python parser.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add proxies.txt
          git commit -m "Auto-update proxy database" || echo "No changes to commit"
          git push

